### ISSUE TITLE
Links that need fixing

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2-site#3]
In 127.0.0.1:4000//glossary/index.html “Tip-Date” section, A program that can obtain …

http://127.0.0.1:4000/blogindex.html all links were changed, for example, http://0.0.7.226/01/17/what-is-new-in-v2.4.8.html

1) I had “ERROR `/favicon.ico' not found” error message in my Jekyll console. I could not find “favicon.ico” anywhere in the folders, and also seemed nothing happened in the webpages. But I think you’d better to have further investigation.
 
3) I may be wrong, but it seems https://galaxy.pasteur.fr/forms::tipdate not available now.  
 
5) In the http://127.0.0.1:4000//BEAUti/index.html, BEAST link http://127.0.0.1:4000///BEAST/index.html looked wired to me, which was BEAST 1 vs. BEAST 2 benchmark rather than a software introduction. In addition, link  http://127.0.0.1:4000/BEAST/ that appeared several different places was the same problem. 
It is now changed into {{site.baseurl}}/, which seemed to solve the problem, but really should have a separate page.

 
9) http://127.0.0.1:4000/snapp-faq/ no xml …?
 
12) In http://www.beast2.org/treeannotator/, http://code.google.com/p/beast-mcmc/wiki/NexusMetacommentFormat should be updated.

**Comment by walterxie** [comment]
I fixed 5), but forgot to add issue number in the commit.

**Comment by rbouckaert** [comment]
All links seem to work now according to https://validator.w3.org/checklink.
